// Generated by Pip Studio's worker before a render. Do not edit or commit.
import type React from 'react';
import {Pip, type PipProps} from './Pip';

export type CharacterProps = PipProps;

export const CHARACTERS: Record<string, React.FC<CharacterProps>> = {
  pip: Pip,
};
